select_origin: directory
files_origin: "./data"
export_target: "./export/"
history: false
focus_max: 2
record_types:
  start:
    fill: "#EF4C4C"
    stroke: "#EF4C4C"
  structure:
    fill: "#00B2D1"
    stroke: "#00B2D1"
  category:
    fill: "#4CEF88"
    stroke: "#4CEF88"
  algorithm:
    fill: "#F136DC"
    stroke: "#F136DC"
  source:
    fill: "#252525"
    stroke: "#252525"
  other:
    fill: "#B3F6CB"
    stroke: "#B3F6CB"
  argument:
    fill: "#858585"
    stroke: "#858585"
  undefined:
    fill: "#858585"
    stroke: "#858585"
link_types:
  # Link to a direct supertype of this node (i.e. a direct broader category)
  is-a:
    stroke: simple
    color: "#C5F136"
    force: 20
  # Link to a direct component of this node
  part:
    color: "#00B2D1"
    stroke: simple
    force: 20
  # Link to an indirect / broad supertype of this node
  is-broadly:
    color: "#C5F136"
    stroke: dash
    force: 1
  # Link to a relevant but not direct/super important component of this node. (i.e. you don't want the two nodes to be super close)
  uses:
    color: "#00B2D1"
    stroke: dash
    force: 1
  # Use to connect to objects that are equivalent
  equivalent:
    stroke: simple
    color: "#000000"
    force: 15
  # Use to mention-link to another nodes
  mention:
    stroke: dash
    color: "#FF8686"
    force: 0
  # Use 
  cites:
    stroke: simple
    color: "#e1e1e1"
    force: 1
  undefined:
    stroke: simple
    color: "#e1e1e1"
references_as_nodes: false
references_type_label: references
record_filters: []
graph_background_color: "#ffffff"
graph_highlight_color: "#ff6a6a"
graph_highlight_on_hover: true
graph_text_size: 6
graph_arrows: true
node_size_method: degree
node_size: 10
node_size_max: 15
node_size_min: 5
attraction_force: 600
attraction_distance_max: 800
attraction_vertical: 0
attraction_horizontal: 0
views: {}
record_metas: []
generate_id: always
link_context: tooltip
hide_id_from_record_header: false
title: "The Automated Reasoning Ontology"
author: "The Automated Reasoners"
description: "Automated Reasoning Ontology"
keywords: []
# link_symbol: ""
# csl: ""
# bibliography: ""
# csl_locale: ""
# css_custom: ""
devtools: false
lang: en
start_page: "start"
