select_origin: directory
files_origin: "./data"
export_target: "./export/"
history: false
focus_max: 2
record_types:
  start:
    fill: "#EF4C4C"
    stroke: "#EF4C4C"
  algorithm:
    fill: "#F136DC"
    stroke: "#F136DC"
  structure:
    fill: "#00B2D1"
    stroke: "#00B2D1"
  category:
    fill: "#4CEF88"
    stroke: "#4CEF88"
  undefined:
    fill: "#858585"
    stroke: "#858585"
  other:
    fill: "#B3F6CB"
    stroke: "#B3F6CB"
  source:
    fill: "#252525"
    stroke: "#252525"
  quote:
    fill: "#F136DC"
    stroke: "#F136DC"
  term:
    fill: "#24009B"
    stroke: "#24009B"
  argument:
    fill: "#858585"
    stroke: "#858585"
link_types:
  subtype: # something is in another category
    stroke: simple
    color: "#C5F136"
  undefined:
    stroke: simple
    color: "#e1e1e1"
  contains:
    stroke: simple
    color: "#000000"
  cites:
    stroke: simple
    color: "#000000"
  uses:
    color: "#00B2D1"
    stroke: simple
references_as_nodes: false
references_type_label: references
record_filters: []
graph_background_color: "#ffffff"
graph_highlight_color: "#ff6a6a"
graph_highlight_on_hover: true
graph_text_size: 6
graph_arrows: true
node_size_method: degree
node_size: 10
node_size_max: 10
node_size_min: 5
attraction_force: 200
attraction_distance_max: 250
attraction_vertical: 0
attraction_horizontal: 0
views: {}
record_metas: []
generate_id: always
link_context: tooltip
hide_id_from_record_header: false
title: "The Automated Reasoning Ontology"
author: "The Automated Reasoners"
description: "Automated Reasoning Ontology"
keywords: []
# link_symbol: ""
# csl: ""
# bibliography: ""
# csl_locale: ""
# css_custom: ""
devtools: false
lang: en
start_page: "start"
